function build_hdcv_mex()
%BUILD_HDCV_MEX Build the native HDCV MATLAB MEX reader.
%
% Run from MATLAB:
%   addpath('/Users/tozturk/PhD/HDCV/matlab')
%   build_hdcv_mex
%
% The compiled hdcv_mex function is written next to this file.

thisDir = fileparts(mfilename('fullpath'));
repoRoot = fileparts(thisDir);
srcDir = fullfile(repoRoot, 'src');

mex('-R2018a', ...
    ['-I' srcDir], ...
    fullfile(thisDir, 'hdcv_mex.c'), ...
    fullfile(srcDir, 'hdcv_utils.c'), ...
    fullfile(srcDir, 'hdcv_metadata.c'), ...
    fullfile(srcDir, 'hdcv_reader.c'), ...
    fullfile(srcDir, 'hdcv_analysis.c'), ...
    '-outdir', thisDir);
end
